syntax = "proto3";
import "Common/Anime.proto";

message get_animes {}

message get_animes_Response {
    repeated Anime animes = 1;
}

message anime_by_genre_Request {
  AnimeGenre anime_genre = 1;
}

message anime_by_genre_Response {
    repeated Anime animes = 1;
}

message anime_by_name_Request {
    string anime_name = 1;
}

message anime_by_name_Response {
    Anime anime = 1;
}

service AnimeRepository {
    rpc GetAnimeRelatedByGenre (anime_by_genre_Request) returns (anime_by_genre_Response);
    rpc GetAnimes (get_animes) returns (get_animes_Response);
    rpc GetAnimeByName (anime_by_name_Request) returns (anime_by_name_Response);
}