syntax = "proto3";

message Achievement {
    string title = 1;
    string description = 2;
    string date = 3;
    string rarity = 4; // Ninguém fala comigo, na minha cabeca deveria ser um enum. Obrigado equipa.
}

message User {
    string username = 1;
    string password = 2;
    optional string location = 3;
    repeated string animes_watched = 4;
    repeated int32 anime_watched_score = 5;
    repeated string topics_subscribed = 6;
    int32 karma = 8;
    repeated Achievement achievements = 9;
}

message get_user_Request {
    string user_name = 1;
}

message get_user_Response {
    User user = 1;
}

message get_all_users_Request {}

message get_all_users_Response {
    repeated User users = 1;
}

service UserRepository {
    rpc GetUser (get_user_Request) returns (get_user_Response);
    rpc GetAllUsers (get_all_users_Request) returns (get_all_users_Response);
}