# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: repository/AnimeRepository.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'repository/AnimeRepository.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
from python.Common import Anime_pb2 as Common_dot_Anime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n repository/AnimeRepository.proto\x1a\x12\x43ommon/Anime.proto\"\x10\n\x0e\x61nimes_Request\")\n\x0f\x61nimes_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\"+\n\x15\x61nime_by_name_Request\x12\x12\n\nanime_name\x18\x01 \x01(\t\"/\n\x16\x61nime_by_name_Response\x12\x15\n\x05\x61nime\x18\x01 \x01(\x0b\x32\x06.Anime\"5\n\x1emultiple_anime_by_name_Request\x12\x13\n\x0b\x61nime_names\x18\x01 \x03(\t\"9\n\x1fmultiple_anime_by_name_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\";\n\x16\x61nime_by_genre_Request\x12!\n\x0c\x61nime_genres\x18\x01 \x03(\x0e\x32\x0b.AnimeGenre\"1\n\x17\x61nime_by_genre_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime2\xa2\x02\n\x0f\x41nimeRepository\x12+\n\x06\x41nimes\x12\x0f.animes_Request\x1a\x10.animes_Response\x12>\n\x0b\x41nimeByName\x12\x16.anime_by_name_Request\x1a\x17.anime_by_name_Response\x12X\n\x13MultipleAnimeByName\x12\x1f.multiple_anime_by_name_Request\x1a .multiple_anime_by_name_Response\x12H\n\x13\x41nimeRelatedByGenre\x12\x17.anime_by_genre_Request\x1a\x18.anime_by_genre_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'repository.AnimeRepository_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANIMES_REQUEST']._serialized_start=56
  _globals['_ANIMES_REQUEST']._serialized_end=72
  _globals['_ANIMES_RESPONSE']._serialized_start=74
  _globals['_ANIMES_RESPONSE']._serialized_end=115
  _globals['_ANIME_BY_NAME_REQUEST']._serialized_start=117
  _globals['_ANIME_BY_NAME_REQUEST']._serialized_end=160
  _globals['_ANIME_BY_NAME_RESPONSE']._serialized_start=162
  _globals['_ANIME_BY_NAME_RESPONSE']._serialized_end=209
  _globals['_MULTIPLE_ANIME_BY_NAME_REQUEST']._serialized_start=211
  _globals['_MULTIPLE_ANIME_BY_NAME_REQUEST']._serialized_end=264
  _globals['_MULTIPLE_ANIME_BY_NAME_RESPONSE']._serialized_start=266
  _globals['_MULTIPLE_ANIME_BY_NAME_RESPONSE']._serialized_end=323
  _globals['_ANIME_BY_GENRE_REQUEST']._serialized_start=325
  _globals['_ANIME_BY_GENRE_REQUEST']._serialized_end=384
  _globals['_ANIME_BY_GENRE_RESPONSE']._serialized_start=386
  _globals['_ANIME_BY_GENRE_RESPONSE']._serialized_end=435
  _globals['_ANIMEREPOSITORY']._serialized_start=438
  _globals['_ANIMEREPOSITORY']._serialized_end=728
# @@protoc_insertion_point(module_scope)
