# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
import python.repository.Anime.AnimeRepository_pb2 as repository_dot_AnimeRepository__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in repository/AnimeRepository_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnimeRepositoryStub(object):
    """--------------------------> SERVICE FOR ANIMEREPOSITORY
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Animes = channel.unary_unary(
                '/AnimeRepository/Animes',
                request_serializer=repository_dot_AnimeRepository__pb2.animes_Request.SerializeToString,
                response_deserializer=repository_dot_AnimeRepository__pb2.animes_Response.FromString,
                _registered_method=True)
        self.AnimeByName = channel.unary_unary(
                '/AnimeRepository/AnimeByName',
                request_serializer=repository_dot_AnimeRepository__pb2.anime_by_name_Request.SerializeToString,
                response_deserializer=repository_dot_AnimeRepository__pb2.anime_by_name_Response.FromString,
                _registered_method=True)
        self.MultipleAnimeByName = channel.unary_unary(
                '/AnimeRepository/MultipleAnimeByName',
                request_serializer=repository_dot_AnimeRepository__pb2.multiple_anime_by_name_Request.SerializeToString,
                response_deserializer=repository_dot_AnimeRepository__pb2.multiple_anime_by_name_Response.FromString,
                _registered_method=True)
        self.AnimeRelatedByGenre = channel.unary_unary(
                '/AnimeRepository/AnimeRelatedByGenre',
                request_serializer=repository_dot_AnimeRepository__pb2.anime_by_genre_Request.SerializeToString,
                response_deserializer=repository_dot_AnimeRepository__pb2.anime_by_genre_Response.FromString,
                _registered_method=True)


class AnimeRepositoryServicer(object):
    """--------------------------> SERVICE FOR ANIMEREPOSITORY
    """

    def Animes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnimeByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultipleAnimeByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnimeRelatedByGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnimeRepositoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Animes': grpc.unary_unary_rpc_method_handler(
                    servicer.Animes,
                    request_deserializer=repository_dot_AnimeRepository__pb2.animes_Request.FromString,
                    response_serializer=repository_dot_AnimeRepository__pb2.animes_Response.SerializeToString,
            ),
            'AnimeByName': grpc.unary_unary_rpc_method_handler(
                    servicer.AnimeByName,
                    request_deserializer=repository_dot_AnimeRepository__pb2.anime_by_name_Request.FromString,
                    response_serializer=repository_dot_AnimeRepository__pb2.anime_by_name_Response.SerializeToString,
            ),
            'MultipleAnimeByName': grpc.unary_unary_rpc_method_handler(
                    servicer.MultipleAnimeByName,
                    request_deserializer=repository_dot_AnimeRepository__pb2.multiple_anime_by_name_Request.FromString,
                    response_serializer=repository_dot_AnimeRepository__pb2.multiple_anime_by_name_Response.SerializeToString,
            ),
            'AnimeRelatedByGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.AnimeRelatedByGenre,
                    request_deserializer=repository_dot_AnimeRepository__pb2.anime_by_genre_Request.FromString,
                    response_serializer=repository_dot_AnimeRepository__pb2.anime_by_genre_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AnimeRepository', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AnimeRepository', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnimeRepository(object):
    """--------------------------> SERVICE FOR ANIMEREPOSITORY
    """

    @staticmethod
    def Animes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AnimeRepository/Animes',
            repository_dot_AnimeRepository__pb2.animes_Request.SerializeToString,
            repository_dot_AnimeRepository__pb2.animes_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnimeByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AnimeRepository/AnimeByName',
            repository_dot_AnimeRepository__pb2.anime_by_name_Request.SerializeToString,
            repository_dot_AnimeRepository__pb2.anime_by_name_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultipleAnimeByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AnimeRepository/MultipleAnimeByName',
            repository_dot_AnimeRepository__pb2.multiple_anime_by_name_Request.SerializeToString,
            repository_dot_AnimeRepository__pb2.multiple_anime_by_name_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnimeRelatedByGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AnimeRepository/AnimeRelatedByGenre',
            repository_dot_AnimeRepository__pb2.anime_by_genre_Request.SerializeToString,
            repository_dot_AnimeRepository__pb2.anime_by_genre_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
