# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: others/AnimeList.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'others/AnimeList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
from python.Common import Anime_pb2 as Common_dot_Anime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16others/AnimeList.proto\x1a\x12\x43ommon/Anime.proto\"\x10\n\x0eget_all_animes\"1\n\x17get_all_animes_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\"/\n\x19get_anime_by_name_Request\x12\x12\n\nanime_name\x18\x01 \x01(\t\"3\n\x1aget_anime_by_name_Response\x12\x15\n\x05\x61nime\x18\x01 \x01(\x0b\x32\x06.Anime\"9\n\"get_multiple_anime_by_name_Request\x12\x13\n\x0b\x61nime_names\x18\x01 \x03(\t\"=\n#get_multiple_anime_by_name_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\"/\n\x19get_similar_anime_Request\x12\x12\n\nanime_name\x18\x01 \x01(\t\"4\n\x1aget_similar_anime_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\"A\n\x1crecomended_animeList_Request\x12!\n\x11\x61nimes_most_liked\x18\x01 \x03(\x0b\x32\x06.Anime\"7\n\x1drecomended_animeList_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime2\x9b\x03\n\tAnimeList\x12\x39\n\x0cGetAllAnimes\x12\x0f.get_all_animes\x1a\x18.get_all_animes_Response\x12I\n\x0eGetAnimeByName\x12\x1a.get_anime_by_name_Request\x1a\x1b.get_anime_by_name_Response\x12\x63\n\x16GetMultipleAnimeByName\x12#.get_multiple_anime_by_name_Request\x1a$.get_multiple_anime_by_name_Response\x12J\n\x0fGetSimilarAnime\x12\x1a.get_similar_anime_Request\x1a\x1b.get_similar_anime_Response\x12W\n\x16GetRecomendedAnimeList\x12\x1d.recomended_animeList_Request\x1a\x1e.recomended_animeList_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'others.AnimeList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GET_ALL_ANIMES']._serialized_start=46
  _globals['_GET_ALL_ANIMES']._serialized_end=62
  _globals['_GET_ALL_ANIMES_RESPONSE']._serialized_start=64
  _globals['_GET_ALL_ANIMES_RESPONSE']._serialized_end=113
  _globals['_GET_ANIME_BY_NAME_REQUEST']._serialized_start=115
  _globals['_GET_ANIME_BY_NAME_REQUEST']._serialized_end=162
  _globals['_GET_ANIME_BY_NAME_RESPONSE']._serialized_start=164
  _globals['_GET_ANIME_BY_NAME_RESPONSE']._serialized_end=215
  _globals['_GET_MULTIPLE_ANIME_BY_NAME_REQUEST']._serialized_start=217
  _globals['_GET_MULTIPLE_ANIME_BY_NAME_REQUEST']._serialized_end=274
  _globals['_GET_MULTIPLE_ANIME_BY_NAME_RESPONSE']._serialized_start=276
  _globals['_GET_MULTIPLE_ANIME_BY_NAME_RESPONSE']._serialized_end=337
  _globals['_GET_SIMILAR_ANIME_REQUEST']._serialized_start=339
  _globals['_GET_SIMILAR_ANIME_REQUEST']._serialized_end=386
  _globals['_GET_SIMILAR_ANIME_RESPONSE']._serialized_start=388
  _globals['_GET_SIMILAR_ANIME_RESPONSE']._serialized_end=440
  _globals['_RECOMENDED_ANIMELIST_REQUEST']._serialized_start=442
  _globals['_RECOMENDED_ANIMELIST_REQUEST']._serialized_end=507
  _globals['_RECOMENDED_ANIMELIST_RESPONSE']._serialized_start=509
  _globals['_RECOMENDED_ANIMELIST_RESPONSE']._serialized_end=564
  _globals['_ANIMELIST']._serialized_start=567
  _globals['_ANIMELIST']._serialized_end=978
# @@protoc_insertion_point(module_scope)
