# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import AnimeList_pb2 as AnimeList__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in AnimeList_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnimeListStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnimeRelatedByGenre = channel.unary_unary(
                '/AnimeList/GetAnimeRelatedByGenre',
                request_serializer=AnimeList__pb2.anime_related_by_genre_Request.SerializeToString,
                response_deserializer=AnimeList__pb2.anime_related_by_genre_Response.FromString,
                _registered_method=True)
        self.GetAnimes = channel.unary_unary(
                '/AnimeList/GetAnimes',
                request_serializer=AnimeList__pb2.get_animes.SerializeToString,
                response_deserializer=AnimeList__pb2.get_animes_Response.FromString,
                _registered_method=True)
        self.GetAnimeByName = channel.unary_unary(
                '/AnimeList/GetAnimeByName',
                request_serializer=AnimeList__pb2.anime_by_name_Request.SerializeToString,
                response_deserializer=AnimeList__pb2.anime_by_name_Response.FromString,
                _registered_method=True)


class AnimeListServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnimeRelatedByGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnimeByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnimeListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnimeRelatedByGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnimeRelatedByGenre,
                    request_deserializer=AnimeList__pb2.anime_related_by_genre_Request.FromString,
                    response_serializer=AnimeList__pb2.anime_related_by_genre_Response.SerializeToString,
            ),
            'GetAnimes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnimes,
                    request_deserializer=AnimeList__pb2.get_animes.FromString,
                    response_serializer=AnimeList__pb2.get_animes_Response.SerializeToString,
            ),
            'GetAnimeByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnimeByName,
                    request_deserializer=AnimeList__pb2.anime_by_name_Request.FromString,
                    response_serializer=AnimeList__pb2.anime_by_name_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AnimeList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AnimeList', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnimeList(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnimeRelatedByGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AnimeList/GetAnimeRelatedByGenre',
            AnimeList__pb2.anime_related_by_genre_Request.SerializeToString,
            AnimeList__pb2.anime_related_by_genre_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AnimeList/GetAnimes',
            AnimeList__pb2.get_animes.SerializeToString,
            AnimeList__pb2.get_animes_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnimeByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AnimeList/GetAnimeByName',
            AnimeList__pb2.anime_by_name_Request.SerializeToString,
            AnimeList__pb2.anime_by_name_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
