syntax = "proto3";

service UserController {
  rpc GetUserStatistics (UserRequest) returns (UserStatistics);
  rpc GetUserRecommendations (UserRequest) returns (UserRecommendations);
  rpc GenerateFeed (UserRequest) returns (Feed);
  rpc GetAchievements (UserRequest) returns (Achievements);
}

message UserRequest {
    string user_id = 1;
}

message UserRecommendations {
    repeated Anime recommended_animes = 1;
}

message FeedTopic {
    string topic = 1;
    string content = 2;
}

message Feed {
    repeated FeedTopic topics = 1;
}

message Achievements {
    repeated Achievement achievements = 1;
}
