syntax = "proto3";
import "Common/Anime.proto";

message get_animes {} // --------------------------> REQUEST FOR GETTING ALL ANIMES

message get_animes_Response {
    repeated Anime animes = 1;
}

message anime_by_name_Request { // ----------------> REQUEST FOR GETTING ANIME BY NAME
    string anime_name = 1;
}

message anime_by_name_Response {
    Anime anime = 1;
}

message get_multiple_anime_Request { // -------------> REQUEST FOR GETTING MORE THAN ONE ANIME
    repeated string anime_name = 1; // List of anime names to get
}

message get_multiple_anime_Response {
    repeated Anime animes = 1;
}

message anime_by_genre_Request { // -------------> REQUEST FOR GETTING ANIME BY GENRE
    AnimeGenre anime_name = 1;
}

message anime_by_genre_Response {
    repeated Anime animes = 1;
}

service AnimeService { // --------------------------> SERVICE FOR ANIME
    rpc GetAnimes (get_animes) returns (get_animes_Response);
    rpc GetAnimeByName (anime_by_name_Request) returns (anime_by_name_Response);
    rpc GetMultipleAnime (get_multiple_anime_Request) returns (get_multiple_anime_Response);
    rpc GetAnimeByGenre (anime_by_genre_Request) returns (anime_by_genre_Response);
}