syntax = "proto3";

service UserService {
    rpc GetUserStatistics (UserRequest) returns (UserStatistics);
    rpc GetUserRecommendations (UserRequest) returns (UserRecommendations);
    rpc GenerateFeed (UserRequest) returns (Feed);
    rpc PublishPost (Post) returns (PostResponse);
    rpc GetAchievements (UserRequest) returns (Achievements);
}

message UserRequest {
    string user_id = 1;
}

message User {
    string username = 1;
    string password = 2;
    string location = 3;
    repeated Anime animes_watched = 4; 
    repeated int32 anime_watched_score = 5;
    repeated string topics_subscribed = 6;
    repeated Message messages_sent = 7;
    int32 karma = 8;
    repeated Achievement achievements = 9;
}

message Feed {
    repeated string posts = 1;
}

message Anime {
    string title = 1;
    string genre = 2;
    int32 episodes_watched = 3;
}

message Message {
    string content = 1;
    string timestamp = 2;
}

message Achievement {
    string name = 1;
    string description = 2;
    string date_earned = 3;
}