# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AnimeService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'AnimeService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x41nimeService.proto\"t\n\x05\x41nime\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x06genres\x18\x02 \x03(\x0e\x32\x0b.AnimeGenre\x12\x10\n\x08\x65pisodes\x18\x03 \x01(\x05\x12\r\n\x05score\x18\x04 \x01(\x02\x12\r\n\x05\x61ired\x18\x05 \x01(\t\x12\x10\n\x08synopsis\x18\x06 \x01(\t\"\x0c\n\nget_animes\"-\n\x13get_animes_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\"%\n\x15\x61nime_by_name_Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x16\x61nime_by_name_Response\x12\x15\n\x05\x61nime\x18\x01 \x01(\x0b\x32\x06.Anime\"/\n\x19get_anime_by_User_Request\x12\x12\n\nanime_name\x18\x01 \x03(\t\"4\n\x1aget_anime_by_User_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\"4\n\x1e\x61nime_related_by_genre_Request\x12\x12\n\nanime_name\x18\x01 \x01(\t\"9\n\x1f\x61nime_related_by_genre_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\";\n\x16\x61nime_by_genre_Request\x12!\n\x0c\x61nime_genres\x18\x01 \x03(\x0e\x32\x0b.AnimeGenre\"1\n\x17\x61nime_by_genre_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime*\x8b\x01\n\nAnimeGenre\x12\n\n\x06\x41\x43TION\x10\x00\x12\r\n\tADVENTURE\x10\x01\x12\n\n\x06\x43OMEDY\x10\x02\x12\t\n\x05\x44RAMA\x10\x03\x12\x0b\n\x07\x46\x41NTASY\x10\x04\x12\n\n\x06HORROR\x10\x05\x12\x0b\n\x07MYSTERY\x10\x06\x12\x0b\n\x07ROMANCE\x10\x07\x12\n\n\x06SCI_FI\x10\x08\x12\x0c\n\x08THRILLER\x10\t2\xef\x02\n\x0c\x41nimeService\x12[\n\x16GetAnimeRelatedByGenre\x12\x1f.anime_related_by_genre_Request\x1a .anime_related_by_genre_Response\x12\x44\n\x0fGetAnimeByGenre\x12\x17.anime_by_genre_Request\x1a\x18.anime_by_genre_Response\x12.\n\tGetAnimes\x12\x0b.get_animes\x1a\x14.get_animes_Response\x12\x41\n\x0eGetAnimeByName\x12\x16.anime_by_name_Request\x1a\x17.anime_by_name_Response\x12I\n\x0eGetAnimeByUser\x12\x1a.get_anime_by_User_Request\x1a\x1b.get_anime_by_User_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AnimeService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANIMEGENRE']._serialized_start=618
  _globals['_ANIMEGENRE']._serialized_end=757
  _globals['_ANIME']._serialized_start=22
  _globals['_ANIME']._serialized_end=138
  _globals['_GET_ANIMES']._serialized_start=140
  _globals['_GET_ANIMES']._serialized_end=152
  _globals['_GET_ANIMES_RESPONSE']._serialized_start=154
  _globals['_GET_ANIMES_RESPONSE']._serialized_end=199
  _globals['_ANIME_BY_NAME_REQUEST']._serialized_start=201
  _globals['_ANIME_BY_NAME_REQUEST']._serialized_end=238
  _globals['_ANIME_BY_NAME_RESPONSE']._serialized_start=240
  _globals['_ANIME_BY_NAME_RESPONSE']._serialized_end=287
  _globals['_GET_ANIME_BY_USER_REQUEST']._serialized_start=289
  _globals['_GET_ANIME_BY_USER_REQUEST']._serialized_end=336
  _globals['_GET_ANIME_BY_USER_RESPONSE']._serialized_start=338
  _globals['_GET_ANIME_BY_USER_RESPONSE']._serialized_end=390
  _globals['_ANIME_RELATED_BY_GENRE_REQUEST']._serialized_start=392
  _globals['_ANIME_RELATED_BY_GENRE_REQUEST']._serialized_end=444
  _globals['_ANIME_RELATED_BY_GENRE_RESPONSE']._serialized_start=446
  _globals['_ANIME_RELATED_BY_GENRE_RESPONSE']._serialized_end=503
  _globals['_ANIME_BY_GENRE_REQUEST']._serialized_start=505
  _globals['_ANIME_BY_GENRE_REQUEST']._serialized_end=564
  _globals['_ANIME_BY_GENRE_RESPONSE']._serialized_start=566
  _globals['_ANIME_BY_GENRE_RESPONSE']._serialized_end=615
  _globals['_ANIMESERVICE']._serialized_start=760
  _globals['_ANIMESERVICE']._serialized_end=1127
# @@protoc_insertion_point(module_scope)
