# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: others/UserRecommendations.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'others/UserRecommendations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
from python.Common import Anime_pb2 as Common_dot_Anime__pb2
from python.Common import User_pb2 as Common_dot_User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n others/UserRecommendations.proto\x1a\x12\x43ommon/Anime.proto\x1a\x11\x43ommon/User.proto\"3\n\x1eusers_related_by_anime_Request\x12\x11\n\tuser_name\x18\x01 \x01(\t\"7\n\x1fusers_related_by_anime_Response\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"5\n users_related_by_message_Request\x12\x11\n\tuser_name\x18\x01 \x01(\t\"9\n!users_related_by_message_Response\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"4\n\x1fusers_related_by_topics_Request\x12\x11\n\tuser_name\x18\x01 \x01(\t\"8\n users_related_by_topics_Response\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"1\n\x1crecomended_animeList_Request\x12\x11\n\tuser_name\x18\x01 \x01(\t\"7\n\x1drecomended_animeList_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime\"G\n&recomended_animeList_by_topics_Request\x12\x1d\n\x15topicnames_subscribed\x18\x01 \x03(\t\"A\n\'recomended_animeList_by_topics_Response\x12\x16\n\x06\x61nimes\x18\x01 \x03(\x0b\x32\x06.Anime2\x83\x04\n\x13UserRecommendations\x12[\n\x16GetUsersRelatedByAnime\x12\x1f.users_related_by_anime_Request\x1a .users_related_by_anime_Response\x12\x61\n\x18GetUsersRelatedByMessage\x12!.users_related_by_message_Request\x1a\".users_related_by_message_Response\x12^\n\x17GetUsersRelatedByTopics\x12 .users_related_by_topics_Request\x1a!.users_related_by_topics_Response\x12W\n\x16GetRecomendedAnimeList\x12\x1d.recomended_animeList_Request\x1a\x1e.recomended_animeList_Response\x12s\n\x1eGetRecomendedAnimeListByTopics\x12\'.recomended_animeList_by_topics_Request\x1a(.recomended_animeList_by_topics_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'others.UserRecommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERS_RELATED_BY_ANIME_REQUEST']._serialized_start=75
  _globals['_USERS_RELATED_BY_ANIME_REQUEST']._serialized_end=126
  _globals['_USERS_RELATED_BY_ANIME_RESPONSE']._serialized_start=128
  _globals['_USERS_RELATED_BY_ANIME_RESPONSE']._serialized_end=183
  _globals['_USERS_RELATED_BY_MESSAGE_REQUEST']._serialized_start=185
  _globals['_USERS_RELATED_BY_MESSAGE_REQUEST']._serialized_end=238
  _globals['_USERS_RELATED_BY_MESSAGE_RESPONSE']._serialized_start=240
  _globals['_USERS_RELATED_BY_MESSAGE_RESPONSE']._serialized_end=297
  _globals['_USERS_RELATED_BY_TOPICS_REQUEST']._serialized_start=299
  _globals['_USERS_RELATED_BY_TOPICS_REQUEST']._serialized_end=351
  _globals['_USERS_RELATED_BY_TOPICS_RESPONSE']._serialized_start=353
  _globals['_USERS_RELATED_BY_TOPICS_RESPONSE']._serialized_end=409
  _globals['_RECOMENDED_ANIMELIST_REQUEST']._serialized_start=411
  _globals['_RECOMENDED_ANIMELIST_REQUEST']._serialized_end=460
  _globals['_RECOMENDED_ANIMELIST_RESPONSE']._serialized_start=462
  _globals['_RECOMENDED_ANIMELIST_RESPONSE']._serialized_end=517
  _globals['_RECOMENDED_ANIMELIST_BY_TOPICS_REQUEST']._serialized_start=519
  _globals['_RECOMENDED_ANIMELIST_BY_TOPICS_REQUEST']._serialized_end=590
  _globals['_RECOMENDED_ANIMELIST_BY_TOPICS_RESPONSE']._serialized_start=592
  _globals['_RECOMENDED_ANIMELIST_BY_TOPICS_RESPONSE']._serialized_end=657
  _globals['_USERRECOMMENDATIONS']._serialized_start=660
  _globals['_USERRECOMMENDATIONS']._serialized_end=1175
# @@protoc_insertion_point(module_scope)
