# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
import python.others.UserRecommendations.UserRecommendations_pb2 as others_dot_UserRecommendations__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in others/UserRecommendations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserRecommendationsStub(object):
    """--------------------------> SERVICE FOR USERRECOMMENDATIONS
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsersRelatedByAnime = channel.unary_unary(
                '/UserRecommendations/GetUsersRelatedByAnime',
                request_serializer=others_dot_UserRecommendations__pb2.users_related_by_anime_Request.SerializeToString,
                response_deserializer=others_dot_UserRecommendations__pb2.users_related_by_anime_Response.FromString,
                _registered_method=True)
        self.GetUsersRelatedByMessage = channel.unary_unary(
                '/UserRecommendations/GetUsersRelatedByMessage',
                request_serializer=others_dot_UserRecommendations__pb2.users_related_by_message_Request.SerializeToString,
                response_deserializer=others_dot_UserRecommendations__pb2.users_related_by_message_Response.FromString,
                _registered_method=True)
        self.GetUsersRelatedByTopics = channel.unary_unary(
                '/UserRecommendations/GetUsersRelatedByTopics',
                request_serializer=others_dot_UserRecommendations__pb2.users_related_by_topics_Request.SerializeToString,
                response_deserializer=others_dot_UserRecommendations__pb2.users_related_by_topics_Response.FromString,
                _registered_method=True)
        self.GetRecomendedAnimeListByTopics = channel.unary_unary(
                '/UserRecommendations/GetRecomendedAnimeListByTopics',
                request_serializer=others_dot_UserRecommendations__pb2.recomended_animeList_by_topics_Request.SerializeToString,
                response_deserializer=others_dot_UserRecommendations__pb2.recomended_animeList_by_topics_Response.FromString,
                _registered_method=True)


class UserRecommendationsServicer(object):
    """--------------------------> SERVICE FOR USERRECOMMENDATIONS
    """

    def GetUsersRelatedByAnime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersRelatedByMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersRelatedByTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecomendedAnimeListByTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserRecommendationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsersRelatedByAnime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersRelatedByAnime,
                    request_deserializer=others_dot_UserRecommendations__pb2.users_related_by_anime_Request.FromString,
                    response_serializer=others_dot_UserRecommendations__pb2.users_related_by_anime_Response.SerializeToString,
            ),
            'GetUsersRelatedByMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersRelatedByMessage,
                    request_deserializer=others_dot_UserRecommendations__pb2.users_related_by_message_Request.FromString,
                    response_serializer=others_dot_UserRecommendations__pb2.users_related_by_message_Response.SerializeToString,
            ),
            'GetUsersRelatedByTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersRelatedByTopics,
                    request_deserializer=others_dot_UserRecommendations__pb2.users_related_by_topics_Request.FromString,
                    response_serializer=others_dot_UserRecommendations__pb2.users_related_by_topics_Response.SerializeToString,
            ),
            'GetRecomendedAnimeListByTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecomendedAnimeListByTopics,
                    request_deserializer=others_dot_UserRecommendations__pb2.recomended_animeList_by_topics_Request.FromString,
                    response_serializer=others_dot_UserRecommendations__pb2.recomended_animeList_by_topics_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserRecommendations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserRecommendations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserRecommendations(object):
    """--------------------------> SERVICE FOR USERRECOMMENDATIONS
    """

    @staticmethod
    def GetUsersRelatedByAnime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRecommendations/GetUsersRelatedByAnime',
            others_dot_UserRecommendations__pb2.users_related_by_anime_Request.SerializeToString,
            others_dot_UserRecommendations__pb2.users_related_by_anime_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersRelatedByMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRecommendations/GetUsersRelatedByMessage',
            others_dot_UserRecommendations__pb2.users_related_by_message_Request.SerializeToString,
            others_dot_UserRecommendations__pb2.users_related_by_message_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersRelatedByTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRecommendations/GetUsersRelatedByTopics',
            others_dot_UserRecommendations__pb2.users_related_by_topics_Request.SerializeToString,
            others_dot_UserRecommendations__pb2.users_related_by_topics_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecomendedAnimeListByTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRecommendations/GetRecomendedAnimeListByTopics',
            others_dot_UserRecommendations__pb2.recomended_animeList_by_topics_Request.SerializeToString,
            others_dot_UserRecommendations__pb2.recomended_animeList_by_topics_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
