# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Common/Anime.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Common/Anime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43ommon/Anime.proto\"t\n\x05\x41nime\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x06genres\x18\x02 \x03(\x0e\x32\x0b.AnimeGenre\x12\x10\n\x08\x65pisodes\x18\x03 \x01(\x05\x12\r\n\x05score\x18\x04 \x01(\x02\x12\r\n\x05\x61ired\x18\x05 \x01(\t\x12\x10\n\x08synopsis\x18\x06 \x01(\t*\x8b\x01\n\nAnimeGenre\x12\n\n\x06\x41\x43TION\x10\x00\x12\r\n\tADVENTURE\x10\x01\x12\n\n\x06\x43OMEDY\x10\x02\x12\t\n\x05\x44RAMA\x10\x03\x12\x0b\n\x07\x46\x41NTASY\x10\x04\x12\n\n\x06HORROR\x10\x05\x12\x0b\n\x07MYSTERY\x10\x06\x12\x0b\n\x07ROMANCE\x10\x07\x12\n\n\x06SCI_FI\x10\x08\x12\x0c\n\x08THRILLER\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Common.Anime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANIMEGENRE']._serialized_start=141
  _globals['_ANIMEGENRE']._serialized_end=280
  _globals['_ANIME']._serialized_start=22
  _globals['_ANIME']._serialized_end=138
# @@protoc_insertion_point(module_scope)
