# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobufs.others import FeedGenerator_pb2 as protobufs_dot_others_dot_FeedGenerator__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobufs/others/FeedGenerator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeedGeneratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFeed = channel.unary_unary(
                '/FeedGeneratorService/GetFeed',
                request_serializer=protobufs_dot_others_dot_FeedGenerator__pb2.FeedRequest.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_FeedGenerator__pb2.FeedResponse.FromString,
                _registered_method=True)
        self.GetTopicFeed = channel.unary_unary(
                '/FeedGeneratorService/GetTopicFeed',
                request_serializer=protobufs_dot_others_dot_FeedGenerator__pb2.TopicFeedRequest.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_FeedGenerator__pb2.TopicFeedResponse.FromString,
                _registered_method=True)


class FeedGeneratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopicFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeed,
                    request_deserializer=protobufs_dot_others_dot_FeedGenerator__pb2.FeedRequest.FromString,
                    response_serializer=protobufs_dot_others_dot_FeedGenerator__pb2.FeedResponse.SerializeToString,
            ),
            'GetTopicFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopicFeed,
                    request_deserializer=protobufs_dot_others_dot_FeedGenerator__pb2.TopicFeedRequest.FromString,
                    response_serializer=protobufs_dot_others_dot_FeedGenerator__pb2.TopicFeedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FeedGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FeedGeneratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeedGeneratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedGeneratorService/GetFeed',
            protobufs_dot_others_dot_FeedGenerator__pb2.FeedRequest.SerializeToString,
            protobufs_dot_others_dot_FeedGenerator__pb2.FeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopicFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedGeneratorService/GetTopicFeed',
            protobufs_dot_others_dot_FeedGenerator__pb2.TopicFeedRequest.SerializeToString,
            protobufs_dot_others_dot_FeedGenerator__pb2.TopicFeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
