syntax = "proto3";
import "Common/Topic.proto";

message GetTopicsRequestPub {}

message GetTopicsResponsePub {
    repeated Topic topics = 1;
}

message CreateTopicRequestPub {
    string topicname = 1;
}

message CreateTopicResponsePub {
    string topicname = 1;
}

message GetTopicRequestPub {
    string topicname = 1;
}

message GetTopicResponsePub {
    Topic topic = 1;
}

message PublishInTopicRequestPub {
    string topicname = 1;
    string publicationname = 2;
    oneof content {
        Message message = 3;
        Image image = 4;
    }
}

message PublishInTopicResponsePub {
    string publicationname = 1;
}

service Publisher {
    rpc GetTopics (GetTopicsRequestPub) returns (GetTopicsResponsePub);
    rpc CreateTopic (CreateTopicRequestPub) returns (CreateTopicResponsePub);
    rpc GetTopic (GetTopicRequestPub) returns (GetTopicResponsePub);
    rpc Publish (PublishInTopicRequestPub) returns (PublishInTopicResponsePub);
}