syntax = "proto3";

import "Common/Anime.proto";

message Empty {}

message User {
    string username = 1;
    string password = 2;
    optional string location = 3;
    repeated string animes_watched = 4;
    repeated int32 anime_watched_score = 5;
    repeated string topics_subscribed = 6;
    int32 karma = 8;
    repeated Achievement achievements = 9;
}

message Topic {
    string topicname = 1;
    repeated Subscriber subscribers = 2;
    repeated Publication publications = 3;
}

message MostUsedTopics {
    repeated Topic most_used_topics = 1;
}

message Top10_Request{
    string user_name = 1;
}

message Top10_Response{
    repeated Anime animes = 1;
}

message KarmaResponse {
    int karma_Value = 1;
}

service UserStatisticsService {
    rpc GetMostUsedTopics (Empty) returns (MostUsedTopics); //Prob broken
    rpc GetTop10 (Top10_Request) returns (Top10_Response);
    rpc GetUserKarma (Empty) returns (KarmaResponse);
}