openapi: 3.0.0
info:
  title: "USER REST API"
  description: "An API about users"
  version: "1.0.0"

servers:
  - url: "/"

components:
  # Schemas used in the API 
  schemas:
    User: # User schema that represents a user
      type: "object"
      required:
        - username
        - password
        - location
        - anime_watched
        - anime_watched_score
        - topics_subscribed
        - messages_sent
        - karma
        - achievements
      properties:
        username:
          type: "string"
        password:
          type: "string"
        location:
          type: "string"
        anime_watched:
          type: "array"
          items:
            type: "string"
        anime_watched_score:
          type: "array"
          items:
            type: "integer"
        topics_subscribed:
          type: "array"
          items:
            type: "string"
        karma:
          type: "integer"
        achievements:
          type: "array"
          items:
             $ref: "#/components/schemas/Achievement"
    Achievement: # Achievement schema that represents a Achievement
      type: "object"
      required: 
        - name
        - description
        - date
        - rarity
      properties:
        name:
          type: "string"
        description:
          type: "string"
        date:
          type: "string"
        rarity:
          type: "string"
          enum: [common, rare, epic, legendary, mythic]
    Anime: #Anime schema that represents an anime
      type: "object"
      required:
        - name
        - genres
        - episodes
        - score
        - aired
        - synopsis
      properties:
        name:
          type: "string"
        genres:
          type: "array"
          items:
            type: "string"
        episodes:
          type: "integer"
        score:
          type: "number"
        aired:
          type: "string"
        synopsis:
          type: "string"
    Topic: # Topic schema that represents a Topic
      type: "object"
      required: 
        - name
        - subscribers
        - publications
      properties:
        name:
          type: "string"
        subscribers:
          type: "array"
          items:
            type: "string"
        publications: 
          type: "array"
          items:
            $ref: "#/components/schemas/Publication"
    Publication: # Publication schema that represents a Publication
      type: "object"
      required: 
        - name
        - topic_name
      properties:
        name:
          type: "string"
        topic_name:
          type: "string"
        message:
          $ref: "#/components/schemas/Message"
        images: 
          type: "array"
          items:
            $ref: "#/components/schemas/Image"
    Image: # Image schema that represents a Image
      type: "object"
      required: 
        - name
      properties:
        name:
          type: "string"
    Message: # Message schema that represents a message
      type: "object"
      required:
        - username
        - content
      properties:
        username:
          type: "string"
        content:
          type: "string"


  # Parameters for paths 
  parameters:
    user_name:
      name: "user_name"
      description: "Name of the user in question"
      in: path
      required: True
      schema:
        type: "string"
    title:
      name: "title"
      description: "Name of the achievement"
      in: path
      required: True
      schema:
        type: "string"
    karma_value:
      name: "karma_value"
      description: "Karma value to update"
      in: path
      required: True
      schema:
        type: "integer"


  # ====================================================
  # ======================= User =======================
  # ====================================================
paths:


  # Health Check Endpoint
  /healthz:
    get:
      operationId: "user_controller.healthz"
      tags:
        - Health
      summary: "Check if the service is alive"
      responses:
        "200":
          description: "Service is alive"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"

  # Readiness Check Endpoint
  /readiness:
    get:
      operationId: "user_controller.readiness"
      tags:
        - Health
      summary: "Check if the service is ready to serve traffic"
      responses:
        "200":
          description: "Service is ready"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"

  # Startup Check Endpoint
  /startup:
    get:
      operationId: "user_controller.startup"
      tags:
        - Health
      summary: "Check if the service has started successfully"
      responses:
        "200":
          description: "Service has started"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"

  /user:
    get:
      operationId: "user_controller.all_users"
      tags:
        - User
      summary: "Show all users"
      responses:
        "200":
          description: "Successfully show all users"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/User"
        
  /user/{user_name}:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
    get:
      operationId: "user_controller.get_user"
      tags:
        - User
      summary: "Get a specific user by username"
      responses:
        "200":
          description: "Successfully retrieved user"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: "User not found"

  /user/{user_name}/related_by_anime:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
    get:
      operationId: "user_controller.get_related_by_anime"
      tags:
        - User
      summary: "Show related users to the specific user based on anime watched"
      responses:
        "200":
          description: "Successfully show related users"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/User"
        "404":
          description: "User not found"


  /user/{user_name}/achievements:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
    get:
      operationId: "user_controller.GetAchivementList"
      tags:
        - User
      summary: "Show user achievements"
      responses:
        "200":
          description: "Successfully show user achievements"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Achievement"
        "404":
          description: "User not found"

  /user/{user_name}/achievement/{title}:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
      - name: "title"
        in: path
        required: true
        description: "Name of the achievement"
        schema:
          type: "string"
    get:
      operationId: "user_controller.UpdateAchievement"
      tags:
        - User
      summary: "Update user achievement"
      responses:
        "201":
          description: "Successfully updated user"
          content:
            application/json:
              schema:
                type: "boolean"
        "404":
          description: "User or achievement not found"
          
  /user/achievement/{title}:
    parameters:
      - name: "title"
        in: path
        required: true
        description: "Name of the achievement"
        schema:
          type: "string"
    get:
      operationId: "user_controller.GetAchievement"
      tags:
        - User
      summary: "Get a specific achievement by name"
      responses:
        "200":
          description: "Successfully retrieved achievement"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Achievement"
        "404":
          description: "Achievement not found"  

  /user/{user_name}/karma:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
    get:
      operationId: "user_controller.get_karma"
      tags:
        - User
      summary: "Show user karma"
      responses:
        "200":
          description: "Successfully show user karma"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/User"
        "404":
          description: "User not found"

  /user/{user_name}/karma/{karma_value}:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
      - name: "karma_value"
        in: path
        required: true
        description: "Karma value to update"
        schema:
          type: "integer"
    get:
      operationId: "user_controller.update_user_karma"
      tags:
        - User
      summary: "Update user karma"
      responses:
        "201":
          description: "Successfully updated user"
          content:
            application/json:
              schema:
                type: "boolean"
        "404":
          description: "User not found"

  /user/{user_name}/top10anime:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
    get:
      operationId: "user_controller.top10Anime"
      tags:
        - User
      summary: "Get the top 10 anime for a specific user"
      responses:
        "200":
          description: "Successfully retrieved top 10 anime"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Anime"
        "404":
          description: "User not found"

  /user/{user_name}/list_topics:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
    get:
      operationId: "user_controller.list_topics"
      tags:
        - User
      summary: "Get the most used topics for a specific user"
      responses:
        "200":
          description: "Successfully retrieved most used topics"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Topic"
        "404":
          description: "User not found"
  

  /user/{user_name}/get_feed:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
    get:
      operationId: "user_controller.get_user_feed"
      tags:
        - User
      summary: "Get all topic publications for a specific user"
      responses:
        "200":
          description: "Successfully retrieved all topics publications"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Publication"
        "404":
          description: "User not found"

  /user/{user_name}/get_topic_feed:
    parameters:
      - name: "user_name"
        in: path
        required: true
        description: "Name of the user"
        schema:
          type: "string"
    get:
      operationId: "user_controller.get_user_topic_feed"
      tags:
        - User
      summary: "Get all topics for a specific user"
      responses:
        "200":
          description: "Successfully retrieved all topics"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Topic"
        "404":
          description: "User not found"
  