# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
import python.repository.User.UserRepository_pb2 as repository_dot_UserRepository__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in repository/UserRepository_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserRepositoryStub(object):
    """--------------------------> SERVICE FOR USERREPOSITORY
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/UserRepository/GetUser',
                request_serializer=repository_dot_UserRepository__pb2.get_user_Request.SerializeToString,
                response_deserializer=repository_dot_UserRepository__pb2.get_user_Response.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_unary(
                '/UserRepository/GetAllUsers',
                request_serializer=repository_dot_UserRepository__pb2.get_all_users_Request.SerializeToString,
                response_deserializer=repository_dot_UserRepository__pb2.get_all_users_Response.FromString,
                _registered_method=True)
        self.GetUsersThatWatchedAnime = channel.unary_unary(
                '/UserRepository/GetUsersThatWatchedAnime',
                request_serializer=repository_dot_UserRepository__pb2.get_users_that_watched_anime_Request.SerializeToString,
                response_deserializer=repository_dot_UserRepository__pb2.get_users_that_watched_anime_Response.FromString,
                _registered_method=True)


class UserRepositoryServicer(object):
    """--------------------------> SERVICE FOR USERREPOSITORY
    """

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersThatWatchedAnime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserRepositoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=repository_dot_UserRepository__pb2.get_user_Request.FromString,
                    response_serializer=repository_dot_UserRepository__pb2.get_user_Response.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=repository_dot_UserRepository__pb2.get_all_users_Request.FromString,
                    response_serializer=repository_dot_UserRepository__pb2.get_all_users_Response.SerializeToString,
            ),
            'GetUsersThatWatchedAnime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersThatWatchedAnime,
                    request_deserializer=repository_dot_UserRepository__pb2.get_users_that_watched_anime_Request.FromString,
                    response_serializer=repository_dot_UserRepository__pb2.get_users_that_watched_anime_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserRepository', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserRepository', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserRepository(object):
    """--------------------------> SERVICE FOR USERREPOSITORY
    """

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRepository/GetUser',
            repository_dot_UserRepository__pb2.get_user_Request.SerializeToString,
            repository_dot_UserRepository__pb2.get_user_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRepository/GetAllUsers',
            repository_dot_UserRepository__pb2.get_all_users_Request.SerializeToString,
            repository_dot_UserRepository__pb2.get_all_users_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersThatWatchedAnime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRepository/GetUsersThatWatchedAnime',
            repository_dot_UserRepository__pb2.get_users_that_watched_anime_Request.SerializeToString,
            repository_dot_UserRepository__pb2.get_users_that_watched_anime_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
