# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
import python.others.Achievements.Achievements_pb2 as protobufs_dot_others_dot_Achievements__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobufs/others/Achievements_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AchievementsControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAchivementList = channel.unary_unary(
                '/AchievementsController/GetAchivementList',
                request_serializer=protobufs_dot_others_dot_Achievements__pb2.AchievementListRequest.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_Achievements__pb2.AchievementListResponse.FromString,
                _registered_method=True)
        self.GetAchievement = channel.unary_unary(
                '/AchievementsController/GetAchievement',
                request_serializer=protobufs_dot_others_dot_Achievements__pb2.AchievementRequest.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_Achievements__pb2.AchievementResponse.FromString,
                _registered_method=True)
        self.UpdateAchievement = channel.unary_unary(
                '/AchievementsController/UpdateAchievement',
                request_serializer=protobufs_dot_others_dot_Achievements__pb2.UpdateRequest.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_Achievements__pb2.UpdateResponse.FromString,
                _registered_method=True)


class AchievementsControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAchivementList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAchievement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAchievement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AchievementsControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAchivementList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAchivementList,
                    request_deserializer=protobufs_dot_others_dot_Achievements__pb2.AchievementListRequest.FromString,
                    response_serializer=protobufs_dot_others_dot_Achievements__pb2.AchievementListResponse.SerializeToString,
            ),
            'GetAchievement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAchievement,
                    request_deserializer=protobufs_dot_others_dot_Achievements__pb2.AchievementRequest.FromString,
                    response_serializer=protobufs_dot_others_dot_Achievements__pb2.AchievementResponse.SerializeToString,
            ),
            'UpdateAchievement': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAchievement,
                    request_deserializer=protobufs_dot_others_dot_Achievements__pb2.UpdateRequest.FromString,
                    response_serializer=protobufs_dot_others_dot_Achievements__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AchievementsController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AchievementsController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AchievementsController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAchivementList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AchievementsController/GetAchivementList',
            protobufs_dot_others_dot_Achievements__pb2.AchievementListRequest.SerializeToString,
            protobufs_dot_others_dot_Achievements__pb2.AchievementListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAchievement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AchievementsController/GetAchievement',
            protobufs_dot_others_dot_Achievements__pb2.AchievementRequest.SerializeToString,
            protobufs_dot_others_dot_Achievements__pb2.AchievementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAchievement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AchievementsController/UpdateAchievement',
            protobufs_dot_others_dot_Achievements__pb2.UpdateRequest.SerializeToString,
            protobufs_dot_others_dot_Achievements__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
