# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Publisher.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Publisher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fPublisher.proto\"\x1a\n\nSubscriber\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\x07Message\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x15\n\x05Image\x12\x0c\n\x04name\x18\x01 \x01(\t\"p\n\x0bPublication\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\ttopicname\x18\x02 \x01(\t\x12\x1b\n\x07message\x18\x03 \x01(\x0b\x32\x08.MessageH\x00\x12\x18\n\x06images\x18\x04 \x01(\x0b\x32\x06.ImageH\x00\x42\t\n\x07\x63ontent\"`\n\x05Topic\x12\x11\n\ttopicname\x18\x01 \x01(\t\x12 \n\x0bsubscribers\x18\x02 \x03(\x0b\x32\x0b.Subscriber\x12\"\n\x0cpublications\x18\x03 \x03(\x0b\x32\x0c.Publication\"\x12\n\x10GetTopicsRequest\"+\n\x11GetTopicsResponse\x12\x16\n\x06topics\x18\x01 \x03(\x0b\x32\x06.Topic\"\'\n\x12\x43reateTopicRequest\x12\x11\n\ttopicname\x18\x01 \x01(\t\"(\n\x13\x43reateTopicResponse\x12\x11\n\ttopicname\x18\x01 \x01(\t\"$\n\x0fGetTopicRequest\x12\x11\n\ttopicname\x18\x01 \x01(\t\")\n\x10GetTopicResponse\x12\x15\n\x05topic\x18\x01 \x01(\x0b\x32\x06.Topic\"{\n\x15PublishInTopicRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x11\n\ttopicname\x18\x02 \x01(\t\x12\x1b\n\x07message\x18\x03 \x01(\x0b\x32\x08.MessageH\x00\x12\x17\n\x05image\x18\x04 \x01(\x0b\x32\x06.ImageH\x00\x42\t\n\x07\x63ontent\"1\n\x16PublishInTopicResponse\x12\x17\n\x0fpublicationname\x18\x01 \x01(\t\"3\n\x0cKarmaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\npost_count\x18\x02 \x01(\x05\"6\n\rKarmaResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0ckarma_points\x18\x02 \x01(\x05\x32\x8e\x02\n\tPublisher\x12\x32\n\tGetTopics\x12\x11.GetTopicsRequest\x1a\x12.GetTopicsResponse\x12\x38\n\x0b\x43reateTopic\x12\x13.CreateTopicRequest\x1a\x14.CreateTopicResponse\x12/\n\x08GetTopic\x12\x10.GetTopicRequest\x1a\x11.GetTopicResponse\x12:\n\x07Publish\x12\x16.PublishInTopicRequest\x1a\x17.PublishInTopicResponse\x12&\n\x05Karma\x12\r.KarmaRequest\x1a\x0e.KarmaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Publisher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBER']._serialized_start=19
  _globals['_SUBSCRIBER']._serialized_end=45
  _globals['_MESSAGE']._serialized_start=47
  _globals['_MESSAGE']._serialized_end=91
  _globals['_IMAGE']._serialized_start=93
  _globals['_IMAGE']._serialized_end=114
  _globals['_PUBLICATION']._serialized_start=116
  _globals['_PUBLICATION']._serialized_end=228
  _globals['_TOPIC']._serialized_start=230
  _globals['_TOPIC']._serialized_end=326
  _globals['_GETTOPICSREQUEST']._serialized_start=328
  _globals['_GETTOPICSREQUEST']._serialized_end=346
  _globals['_GETTOPICSRESPONSE']._serialized_start=348
  _globals['_GETTOPICSRESPONSE']._serialized_end=391
  _globals['_CREATETOPICREQUEST']._serialized_start=393
  _globals['_CREATETOPICREQUEST']._serialized_end=432
  _globals['_CREATETOPICRESPONSE']._serialized_start=434
  _globals['_CREATETOPICRESPONSE']._serialized_end=474
  _globals['_GETTOPICREQUEST']._serialized_start=476
  _globals['_GETTOPICREQUEST']._serialized_end=512
  _globals['_GETTOPICRESPONSE']._serialized_start=514
  _globals['_GETTOPICRESPONSE']._serialized_end=555
  _globals['_PUBLISHINTOPICREQUEST']._serialized_start=557
  _globals['_PUBLISHINTOPICREQUEST']._serialized_end=680
  _globals['_PUBLISHINTOPICRESPONSE']._serialized_start=682
  _globals['_PUBLISHINTOPICRESPONSE']._serialized_end=731
  _globals['_KARMAREQUEST']._serialized_start=733
  _globals['_KARMAREQUEST']._serialized_end=784
  _globals['_KARMARESPONSE']._serialized_start=786
  _globals['_KARMARESPONSE']._serialized_end=840
  _globals['_PUBLISHER']._serialized_start=843
  _globals['_PUBLISHER']._serialized_end=1113
# @@protoc_insertion_point(module_scope)
