# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: others/Publisher.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'others/Publisher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
from python.Common import Topic_pb2 as Common_dot_Topic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16others/Publisher.proto\x1a\x12\x43ommon/Topic.proto\"\x15\n\x13GetTopicsRequestPub\".\n\x14GetTopicsResponsePub\x12\x16\n\x06topics\x18\x01 \x03(\x0b\x32\x06.Topic\"*\n\x15\x43reateTopicRequestPub\x12\x11\n\ttopicname\x18\x01 \x01(\t\"+\n\x16\x43reateTopicResponsePub\x12\x11\n\ttopicname\x18\x01 \x01(\t\"\'\n\x12GetTopicRequestPub\x12\x11\n\ttopicname\x18\x01 \x01(\t\",\n\x13GetTopicResponsePub\x12\x15\n\x05topic\x18\x01 \x01(\x0b\x32\x06.Topic\"\x87\x01\n\x18PublishInTopicRequestPub\x12\x11\n\ttopicname\x18\x01 \x01(\t\x12\x17\n\x0fpublicationname\x18\x02 \x01(\t\x12\x1b\n\x07message\x18\x03 \x01(\x0b\x32\x08.MessageH\x00\x12\x17\n\x05image\x18\x04 \x01(\x0b\x32\x06.ImageH\x00\x42\t\n\x07\x63ontent\"4\n\x19PublishInTopicResponsePub\x12\x17\n\x0fpublicationname\x18\x01 \x01(\t\"\x11\n\x0fKarmaRequestPub\"(\n\x10KarmaResponsePub\x12\x14\n\x0ckarma_points\x18\x01 \x01(\x05\x32\xac\x02\n\tPublisher\x12\x38\n\tGetTopics\x12\x14.GetTopicsRequestPub\x1a\x15.GetTopicsResponsePub\x12>\n\x0b\x43reateTopic\x12\x16.CreateTopicRequestPub\x1a\x17.CreateTopicResponsePub\x12\x35\n\x08GetTopic\x12\x13.GetTopicRequestPub\x1a\x14.GetTopicResponsePub\x12@\n\x07Publish\x12\x19.PublishInTopicRequestPub\x1a\x1a.PublishInTopicResponsePub\x12,\n\x05Karma\x12\x10.KarmaRequestPub\x1a\x11.KarmaResponsePubb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'others.Publisher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTOPICSREQUESTPUB']._serialized_start=46
  _globals['_GETTOPICSREQUESTPUB']._serialized_end=67
  _globals['_GETTOPICSRESPONSEPUB']._serialized_start=69
  _globals['_GETTOPICSRESPONSEPUB']._serialized_end=115
  _globals['_CREATETOPICREQUESTPUB']._serialized_start=117
  _globals['_CREATETOPICREQUESTPUB']._serialized_end=159
  _globals['_CREATETOPICRESPONSEPUB']._serialized_start=161
  _globals['_CREATETOPICRESPONSEPUB']._serialized_end=204
  _globals['_GETTOPICREQUESTPUB']._serialized_start=206
  _globals['_GETTOPICREQUESTPUB']._serialized_end=245
  _globals['_GETTOPICRESPONSEPUB']._serialized_start=247
  _globals['_GETTOPICRESPONSEPUB']._serialized_end=291
  _globals['_PUBLISHINTOPICREQUESTPUB']._serialized_start=294
  _globals['_PUBLISHINTOPICREQUESTPUB']._serialized_end=429
  _globals['_PUBLISHINTOPICRESPONSEPUB']._serialized_start=431
  _globals['_PUBLISHINTOPICRESPONSEPUB']._serialized_end=483
  _globals['_KARMAREQUESTPUB']._serialized_start=485
  _globals['_KARMAREQUESTPUB']._serialized_end=502
  _globals['_KARMARESPONSEPUB']._serialized_start=504
  _globals['_KARMARESPONSEPUB']._serialized_end=544
  _globals['_PUBLISHER']._serialized_start=547
  _globals['_PUBLISHER']._serialized_end=847
# @@protoc_insertion_point(module_scope)
