# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import UserService_pb2 as services_dot_UserService__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services/UserService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """--------------------------> SERVICE FOR USERSERVICE
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/UserService/GetUser',
                request_serializer=services_dot_UserService__pb2.get_user_Request.SerializeToString,
                response_deserializer=services_dot_UserService__pb2.get_user_Response.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_unary(
                '/UserService/GetAllUsers',
                request_serializer=services_dot_UserService__pb2.get_all_users_Request.SerializeToString,
                response_deserializer=services_dot_UserService__pb2.get_all_users_Response.FromString,
                _registered_method=True)
        self.GetUsersRelatedByAnime = channel.unary_unary(
                '/UserService/GetUsersRelatedByAnime',
                request_serializer=services_dot_UserService__pb2.users_related_by_anime_Request.SerializeToString,
                response_deserializer=services_dot_UserService__pb2.users_related_by_anime_Response.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """--------------------------> SERVICE FOR USERSERVICE
    """

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersRelatedByAnime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=services_dot_UserService__pb2.get_user_Request.FromString,
                    response_serializer=services_dot_UserService__pb2.get_user_Response.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=services_dot_UserService__pb2.get_all_users_Request.FromString,
                    response_serializer=services_dot_UserService__pb2.get_all_users_Response.SerializeToString,
            ),
            'GetUsersRelatedByAnime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersRelatedByAnime,
                    request_deserializer=services_dot_UserService__pb2.users_related_by_anime_Request.FromString,
                    response_serializer=services_dot_UserService__pb2.users_related_by_anime_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """--------------------------> SERVICE FOR USERSERVICE
    """

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/GetUser',
            services_dot_UserService__pb2.get_user_Request.SerializeToString,
            services_dot_UserService__pb2.get_user_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/GetAllUsers',
            services_dot_UserService__pb2.get_all_users_Request.SerializeToString,
            services_dot_UserService__pb2.get_all_users_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersRelatedByAnime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserService/GetUsersRelatedByAnime',
            services_dot_UserService__pb2.users_related_by_anime_Request.SerializeToString,
            services_dot_UserService__pb2.users_related_by_anime_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
