# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/UserService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'services/UserService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
from python.Common import User_pb2 as Common_dot_User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aservices/UserService.proto\x1a\x11\x43ommon/User.proto\"%\n\x10get_user_Request\x12\x11\n\tuser_name\x18\x01 \x01(\t\"(\n\x11get_user_Response\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"\x17\n\x15get_all_users_Request\".\n\x16get_all_users_Response\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"5\n\x1eusers_related_by_anime_Request\x12\x13\n\x0b\x61nime_names\x18\x01 \x03(\t\"7\n\x1fusers_related_by_anime_Response\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User2\xdc\x01\n\x0bUserService\x12\x30\n\x07GetUser\x12\x11.get_user_Request\x1a\x12.get_user_Response\x12>\n\x0bGetAllUsers\x12\x16.get_all_users_Request\x1a\x17.get_all_users_Response\x12[\n\x16GetUsersRelatedByAnime\x12\x1f.users_related_by_anime_Request\x1a .users_related_by_anime_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.UserService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GET_USER_REQUEST']._serialized_start=49
  _globals['_GET_USER_REQUEST']._serialized_end=86
  _globals['_GET_USER_RESPONSE']._serialized_start=88
  _globals['_GET_USER_RESPONSE']._serialized_end=128
  _globals['_GET_ALL_USERS_REQUEST']._serialized_start=130
  _globals['_GET_ALL_USERS_REQUEST']._serialized_end=153
  _globals['_GET_ALL_USERS_RESPONSE']._serialized_start=155
  _globals['_GET_ALL_USERS_RESPONSE']._serialized_end=201
  _globals['_USERS_RELATED_BY_ANIME_REQUEST']._serialized_start=203
  _globals['_USERS_RELATED_BY_ANIME_REQUEST']._serialized_end=256
  _globals['_USERS_RELATED_BY_ANIME_RESPONSE']._serialized_start=258
  _globals['_USERS_RELATED_BY_ANIME_RESPONSE']._serialized_end=313
  _globals['_USERSERVICE']._serialized_start=316
  _globals['_USERSERVICE']._serialized_end=536
# @@protoc_insertion_point(module_scope)
