# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')))
import python.others.UserStatistics.UserStatistics_pb2 as protobufs_dot_others_dot_UserStatistics__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobufs/others/UserStatistics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserStatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMostUsedTopics = channel.unary_unary(
                '/UserStatisticsService/GetMostUsedTopics',
                request_serializer=protobufs_dot_others_dot_UserStatistics__pb2.Empty.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.MostUsedTopics.FromString,
                _registered_method=True)
        self.GetTop10 = channel.unary_unary(
                '/UserStatisticsService/GetTop10',
                request_serializer=protobufs_dot_others_dot_UserStatistics__pb2.Top10_Request.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.Top10_Response.FromString,
                _registered_method=True)
        self.GetUserKarma = channel.unary_unary(
                '/UserStatisticsService/GetUserKarma',
                request_serializer=protobufs_dot_others_dot_UserStatistics__pb2.Empty.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.KarmaResponse.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_unary(
                '/UserStatisticsService/GetAllUsers',
                request_serializer=protobufs_dot_others_dot_UserStatistics__pb2.Empty.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.GetAllUsersResponse.FromString,
                _registered_method=True)
        self.GetUserByName = channel.unary_unary(
                '/UserStatisticsService/GetUserByName',
                request_serializer=protobufs_dot_others_dot_UserStatistics__pb2.GetUserByNameRequest.SerializeToString,
                response_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.GetUserByNameResponse.FromString,
                _registered_method=True)


class UserStatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMostUsedTopics(self, request, context):
        """Prob broken
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTop10(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserKarma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserStatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMostUsedTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMostUsedTopics,
                    request_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.Empty.FromString,
                    response_serializer=protobufs_dot_others_dot_UserStatistics__pb2.MostUsedTopics.SerializeToString,
            ),
            'GetTop10': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTop10,
                    request_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.Top10_Request.FromString,
                    response_serializer=protobufs_dot_others_dot_UserStatistics__pb2.Top10_Response.SerializeToString,
            ),
            'GetUserKarma': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserKarma,
                    request_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.Empty.FromString,
                    response_serializer=protobufs_dot_others_dot_UserStatistics__pb2.KarmaResponse.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.Empty.FromString,
                    response_serializer=protobufs_dot_others_dot_UserStatistics__pb2.GetAllUsersResponse.SerializeToString,
            ),
            'GetUserByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByName,
                    request_deserializer=protobufs_dot_others_dot_UserStatistics__pb2.GetUserByNameRequest.FromString,
                    response_serializer=protobufs_dot_others_dot_UserStatistics__pb2.GetUserByNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserStatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserStatisticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserStatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMostUsedTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserStatisticsService/GetMostUsedTopics',
            protobufs_dot_others_dot_UserStatistics__pb2.Empty.SerializeToString,
            protobufs_dot_others_dot_UserStatistics__pb2.MostUsedTopics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTop10(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserStatisticsService/GetTop10',
            protobufs_dot_others_dot_UserStatistics__pb2.Top10_Request.SerializeToString,
            protobufs_dot_others_dot_UserStatistics__pb2.Top10_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserKarma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserStatisticsService/GetUserKarma',
            protobufs_dot_others_dot_UserStatistics__pb2.Empty.SerializeToString,
            protobufs_dot_others_dot_UserStatistics__pb2.KarmaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserStatisticsService/GetAllUsers',
            protobufs_dot_others_dot_UserStatistics__pb2.Empty.SerializeToString,
            protobufs_dot_others_dot_UserStatistics__pb2.GetAllUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserStatisticsService/GetUserByName',
            protobufs_dot_others_dot_UserStatistics__pb2.GetUserByNameRequest.SerializeToString,
            protobufs_dot_others_dot_UserStatistics__pb2.GetUserByNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
