# Configures the ingress to route traffic to the appropriate frontend services.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anime-controller-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" # Use the NGINX ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: / # Rewrite the path if needed
spec:
  rules:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anime-controller # Name of the service
            port:
              number: 50051